- name: clean kernel
  command:
    cmd: make clean
    chdir: "{{ kernel_srcdir }}"
  tags:
    - kernel-clean
- name: build kernel
  command:
    cmd: "make \"$(portageq envvar MAKEOPTS)\" CC=\"distcc gcc $(portageq envvar CFLAGS)\""
    chdir: "{{ kernel_srcdir }}"
  tags:
    - kernel-build
