- name: clean kernel
  command:
    cmd: make clean
    chdir: "{{ kernel_srcdir }}"
  tags:
    - kernel-clean
- name: build kernel
  command:
    cmd: make -j{{ ansible_processor_vcpus + 1 }} CC='gcc -march=native'
    chdir: "{{ kernel_srcdir }}"
  tags:
    - kernel-build
