---
- name: generate a missing config
  shell: "zcat /proc/config.gz >{{ kernel_srcdir }}/.config"
  args:
    creates: "{{ kernel_srcdir }}/.config"
- name: backup existing config
  copy:
    remote_src: yes
    src: "{{ kernel_srcdir }}/.config"
    dest: "{{ kernel_srcdir }}/.config.ansible-backup"
- name: change kernel src config settings
  block:
    - name: write new config
      lineinfile:
        path: "{{ kernel_srcdir }}/.config"
        line: "{{ item.key }}={{ item.value[0:1] if (item.value == 'ym' or item.value == 'my') else item.value }}"
        regexp: "^(#\\s)?{{ item.key }}[= ]"
      loop: "{{ kernel_config_defaults | dict2items }}"
    - name: update kconfig
      shell:
        cmd: "yes '' | make olddefconfig .config"
        chdir: "{{ kernel_srcdir }}"
  rescue:
    - name: restore backed up config
      copy:
        remote_src: yes
        src: "{{ kernel_srcdir }}/.config.ansible-backup"
        dest: "{{ kernel_srcdir }}/.config"
    - name: fail due to prior errors
      command: /bin/false

