---
# Initial ramdisk
- name: genkernel compilation settings
  lineinfile:
    path: /etc/genkernel.conf
    line: "{{ item.key }}=\"{{ item.value }}\""
    regexp: "^(#[\\s]*)?{{ item.key }}="
  with_dict:
    UTILS_CC: "distcc gcc $(portageq envvar CFLAGS)"
    UTILS_CXX: "distcc g++ $(portageq envvar CXXFLAGS)"
    MAKEOPTS: "$(portageq envvar MAKEOPTS)"
  tags:
    - kernel-initramfs
- name: generate and install initial ramdisk
  command:
    cmd: genkernel --kerneldir=. --clear-cachedir --postclear --kernel-config=.config --microcode --lvm --install initramfs
    chdir: "{{ kernel_srcdir }}"
  tags:
    - kernel-initramfs
