---
- name: configure the kernel
  import_tasks: config-vanilla.yml
  tags:
    - kernel-config
- name: build the kernel
  import_tasks: build-vanilla.yml

# OS specific installation tasks.
- name: install the kernel
  include_tasks: "install-{{ ansible_facts['os_family'] | lower }}.yml"
  tags:
    - kernel-install
