- name: install kernel headers
  apt:
    name: "linux-headers-{{ armbian.branch }}-{{ armbian.linux_family }}"
    state: latest

- include_tasks: main-armbian-legacy-rk35xx.yml
  when: (ansible_facts.armbian.linux_family | default('none')) == 'rk35xx' and ansible_facts.armbian.branch == 'legacy'
  tags: always

- name: update kernel cmdline
  import_tasks: cmdline-armbian.yml
