---
- name: install kerneltool
  copy:
    src: kerneltool.sh
    dest: /usr/local/sbin/kerneltool
    mode: 0755
    owner: root
    group: root
  tags:
    - kernel-tool
- name: configure the kernel
  import_tasks: config-vanilla.yml
  tags:
    - kernel-config
- name: build the kernel
  import_tasks: build-vanilla.yml
- name: mount /boot
  shell: mountpoint /boot || mount /boot
  tags:
    - kernel-install
    - kernel-initramfs
    - kernel-bootloader
- name: install the kernel
  import_tasks: install-vanilla.yml

# OS specific installation tasks.
- name: install an initramfs
  include_tasks: "initramfs-{{ ansible_facts['os_family'] | lower }}.yml"
  tags:
    - kernel-initramfs
- name: configure bootloader
  include_tasks: bootloader-grub.yml
  tags:
    - kernel-bootloader
